[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#1c1c1c"
foreground = "#ebdbb2"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "HackNerdFontMono", style = "Regular" }
bold   = { family = "HackNerdFontMono", style = "Bold" }
italic = { family = "HackNerdFontMono", style = "Italic" }
bold_italic = { family = "HackNerdFontMono", style = "Bold Italic" }
size = 16

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = -1
y = 1

[scrolling]
history = 10000

[window.dimensions]
columns = 100
lines = 26
